/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/pandas2ri.py:191: FutureWarning: from_items is deprecated. Please use DataFrame.from_dict(dict(items), ...) instead. DataFrame.from_dict(OrderedDict(items)) may be used to preserve the key order.
  res = PandasDataFrame.from_items(items)
[info] Parsing spec ...
[info] Parsing succeeded
[info] Building synthesizer ...
[info] Synthesizing programs ...
[info] Solution not found!
[info] Synthesizing programs ...
====> run synthesize test_23.json
# num samples per layer: 4
    year        product    Q4    Q3    Q2    Q1
0   2011  Product1_2011   3.0   5.0   5.0  10.0
1   2011  Product2_2011   5.0   7.0   5.0   2.0
2   2011  Product3_2011   3.0   9.0  10.0   7.0
3   2011  Product4_2011   3.0   2.0   8.0   1.0
4   2011  Product5_2011   1.0   7.0   1.0   6.0
5   2011  Product6_2011   9.0   1.0   6.0   1.0
6   2012  Product1_2012   3.0   3.0   6.0   4.0
7   2012  Product2_2012   4.0   3.0   6.0   4.0
8   2012  Product3_2012   3.0   6.0   6.0   4.0
9   2012  Product4_2012   4.0  10.0   6.0   1.0
10  2012  Product5_2012   8.0   5.0   4.0   7.0
11  2012  Product6_2012   8.0   8.0   8.0   6.0
12  2013  Product1_2013  10.0   2.0   3.0   9.0
13  2013  Product2_2013   8.0   6.0   7.0   7.0
14  2013  Product3_2013   9.0   8.0   4.0   9.0
15  2013  Product4_2013   5.0   9.0   5.0   2.0
16  2013  Product5_2013   1.0   5.0   2.0   4.0
17  2013  Product6_2013   8.0  10.0   6.0   4.0
  c_x   c_y  c_color
0  Q3  2013     40.0
1  Q1  2012     26.0
2  Q4  2013     41.0
3  Q3  2012     35.0
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF17759 <- RET_DF17757 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 14


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF17765 <- RET_DF17763 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF17771 <- RET_DF17769 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF20743 <- RET_DF20741 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF20746 <- RET_DF20744 %>% mutate(cumsum=cumsum(.[[2]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF20958 <- RET_DF20956 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 4 (the group size) or one, not 12


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21142 <- RET_DF21140 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21163 <- RET_DF21161 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21168 <- RET_DF21166 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21180 <- RET_DF21178 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 17


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21183 <- RET_DF21181 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 14


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21186 <- RET_DF21184 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21222 <- RET_DF21220 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21227 <- RET_DF21225 %>% mutate(cumsum=cumsum(.[[1]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21230 <- RET_DF21228 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21242 <- RET_DF21240 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 17


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21245 <- RET_DF21243 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 14


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21248 <- RET_DF21246 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 4 (the group size) or one, not 12


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21251 <- RET_DF21249 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21254 <- RET_DF21252 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21257 <- RET_DF21255 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21263 <- RET_DF21261 %>% mutate(cumsum=cumsum(.[[2]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21266 <- RET_DF21264 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21275 <- RET_DF21273 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 1 (the group size), not 17


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21278 <- RET_DF21276 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 14


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21281 <- RET_DF21279 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 4 (the group size) or one, not 12


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21284 <- RET_DF21282 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 16


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21287 <- RET_DF21285 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 5 (the group size) or one, not 13


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21290 <- RET_DF21288 %>% mutate(cumsum=cumsum(.[[3]]))',)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 492, in eval_cumsum
    ret_val = robjects.r(_script)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 352, in __call__
    res = self.eval(p)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 178, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/yufeng/research/vis-pirate/venv/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 106, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
rpy2.rinterface.RRuntimeError: Error in mutate_impl(.data, dots) : 
  Column `cumsum` must be length 2 (the group size) or one, not 15


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 32, in emit
    msg = self.format(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 18, in format
    msg = record.getMessage()
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 380, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "run.py", line 78, in <module>
    test_benchmarks(flags.data_dir, flags.data_id, flags.num_samples, flags.backend, flags.prune)
  File "run.py", line 59, in test_benchmarks
    result = FalxEvalInterface.synthesize(inputs=[input_data], full_trace=trace, num_samples=num_samples, extra_consts=extra_consts, backend=backend, prune=prune)
  File "/Users/yufeng/research/vis-pirate/falx/eval_interface.py", line 47, in synthesize
    candidate_progs = morpheus.synthesize(inputs, sample_output, full_sym_data, prune, extra_consts=extra_consts)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 652, in synthesize
    prog = synthesizer.synthesize()
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/synthesizer/synthesizer.py", line 40, in synthesize
    res = self._decider.analyze(prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 298, in analyze
    return blame_finder.process_examples(self.examples, self.equal_output)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in process_examples
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 240, in <listcomp>
    all_ok = all([self.process_example(example, equal_output) for example in examples])
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 278, in process_example
    interpreter_output = constraint_interpreter.visit(self._prog)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/visitor.py", line 22, in visit
    return visitor(node)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/decider/example_constraint_pruning.py", line 177, in visit_apply_node
    method_output = method(apply_node, in_values)
  File "/Users/yufeng/research/vis-pirate/falx/morpheus.py", line 495, in eval_cumsum
    logger.error('Error in interpreting cumsum...', _script)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Users/yufeng/research/vis-pirate/falx/tyrell/logger.py", line 35, in emit
    self.handleError(record)
Message: 'Error in interpreting cumsum...'
Arguments: ('RET_DF21295 <- RET_DF21293 %>% mutate(cumsum=cumsum(.[[3]]))',)
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting spread...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...
[error] Error in interpreting mutate...

real	11m33.569s
user	9m19.329s
sys	0m14.890s
